apiVersion: v1
kind: Service
metadata:
  name: switch
  labels:
    name: switch
    color: {{ .Values.color }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    name: nginx
    color: {{ .Values.color }}
