apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.color }}-deploy
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: nginx
        color: {{ .Values.color }}
    spec:
      containers:
        - name: nginx
          image: localhost:5000/bgv:{{ .Values.tag }}
          ports:
            - name: http
              containerPort: 80
